import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../controllers/game_state_controller.dart';

class EnvironmentTheme {
  final String id;
  final String name;
  final String ambience;
  final IconData icon;
  final List<Color> skyColors;
  final Color farColor;
  final Color midColor;
  final Color foregroundColor;
  final Color groundTop;
  final Color groundBottom;
  final Color pipeBase;
  final Color pipeRim;
  final Color accent;
  final Color particleColor;
  final Color lightColor;

  const EnvironmentTheme({
    required this.id,
    required this.name,
    required this.ambience,
    required this.icon,
    required this.skyColors,
    required this.farColor,
    required this.midColor,
    required this.foregroundColor,
    required this.groundTop,
    required this.groundBottom,
    required this.pipeBase,
    required this.pipeRim,
    required this.accent,
    required this.particleColor,
    required this.lightColor,
  });

  List<Color> get previewColors => [
        skyColors.first,
        skyColors[skyColors.length ~/ 2],
        groundTop,
      ];

  static EnvironmentTheme current() {
    if (Get.isRegistered<GameStateController>()) {
      return byId(GameStateController.instance.selectedEnvironment.value);
    }
    return byId('forest');
  }

  static EnvironmentTheme byId(String id) {
    return premiumEnvironmentThemes.firstWhere(
      (theme) => theme.id == id || (id == 'default' && theme.id == 'forest'),
      orElse: () => premiumEnvironmentThemes.first,
    );
  }
}

const List<EnvironmentTheme> premiumEnvironmentThemes = [
  EnvironmentTheme(
    id: 'forest',
    name: 'Mystic Forest',
    ambience: 'Fireflies, fog, leaves',
    icon: Icons.forest,
    skyColors: [Color(0xFF071D18), Color(0xFF164A32), Color(0xFF8CCB86)],
    farColor: Color(0xFF17412F),
    midColor: Color(0xFF245F37),
    foregroundColor: Color(0xFF0E261D),
    groundTop: Color(0xFF2F6F35),
    groundBottom: Color(0xFF3A2519),
    pipeBase: Color(0xFF5B3A24),
    pipeRim: Color(0xFF244C28),
    accent: Color(0xFF7BE06C),
    particleColor: Color(0xFFE7FF9E),
    lightColor: Color(0xFFFFECA7),
  ),
  EnvironmentTheme(
    id: 'sunset',
    name: 'Sunset Valley',
    ambience: 'Dust, glow, canyon wind',
    icon: Icons.wb_twilight,
    skyColors: [Color(0xFF481A56), Color(0xFFFF6A3D), Color(0xFFFFC76B)],
    farColor: Color(0xFF7C3652),
    midColor: Color(0xFFA55532),
    foregroundColor: Color(0xFF3E1F22),
    groundTop: Color(0xFFB76735),
    groundBottom: Color(0xFF5C3327),
    pipeBase: Color(0xFFB46A3C),
    pipeRim: Color(0xFF7B3F25),
    accent: Color(0xFFFFD36C),
    particleColor: Color(0xFFFFD9A1),
    lightColor: Color(0xFFFFC35A),
  ),
  EnvironmentTheme(
    id: 'cyber',
    name: 'Neon Cyber City',
    ambience: 'Rain, neon, traffic hum',
    icon: Icons.location_city,
    skyColors: [Color(0xFF040712), Color(0xFF10103B), Color(0xFF2E0F46)],
    farColor: Color(0xFF111A3C),
    midColor: Color(0xFF20155B),
    foregroundColor: Color(0xFF050711),
    groundTop: Color(0xFF111727),
    groundBottom: Color(0xFF03040A),
    pipeBase: Color(0xFF24283F),
    pipeRim: Color(0xFF00D7FF),
    accent: Color(0xFFFF2BD6),
    particleColor: Color(0xFF6EFFF7),
    lightColor: Color(0xFFFF3DF2),
  ),
  EnvironmentTheme(
    id: 'arctic',
    name: 'Frozen Arctic',
    ambience: 'Snow, aurora, cold wind',
    icon: Icons.ac_unit,
    skyColors: [Color(0xFF07152C), Color(0xFF2B6B86), Color(0xFFE2FAFF)],
    farColor: Color(0xFFB7DDEC),
    midColor: Color(0xFF7BAEC6),
    foregroundColor: Color(0xFFEAFBFF),
    groundTop: Color(0xFFEAFBFF),
    groundBottom: Color(0xFF8AB7CD),
    pipeBase: Color(0xFFBFEAFF),
    pipeRim: Color(0xFF5CAACC),
    accent: Color(0xFF78FFE8),
    particleColor: Color(0xFFFFFFFF),
    lightColor: Color(0xFFA7FFE8),
  ),
  EnvironmentTheme(
    id: 'desert',
    name: 'Desert Ruins',
    ambience: 'Sandstorm, heat haze',
    icon: Icons.temple_hindu,
    skyColors: [Color(0xFF6E3F28), Color(0xFFE59B45), Color(0xFFFFD886)],
    farColor: Color(0xFFB97635),
    midColor: Color(0xFFD39447),
    foregroundColor: Color(0xFF6A3C22),
    groundTop: Color(0xFFD89A4C),
    groundBottom: Color(0xFF8E5628),
    pipeBase: Color(0xFFC8914B),
    pipeRim: Color(0xFF806037),
    accent: Color(0xFFFFD36E),
    particleColor: Color(0xFFFFE1A3),
    lightColor: Color(0xFFFFCB69),
  ),
  EnvironmentTheme(
    id: 'ocean',
    name: 'Atlantis Deep Ocean',
    ambience: 'Bubbles, sonar, ruins',
    icon: Icons.water,
    skyColors: [Color(0xFF020B24), Color(0xFF064A68), Color(0xFF1AA6B8)],
    farColor: Color(0xFF05354C),
    midColor: Color(0xFF0A6574),
    foregroundColor: Color(0xFF03202D),
    groundTop: Color(0xFF0C6D69),
    groundBottom: Color(0xFF04303E),
    pipeBase: Color(0xFF496B67),
    pipeRim: Color(0xFF19DAC9),
    accent: Color(0xFF5CFFF1),
    particleColor: Color(0xFFBFFFF8),
    lightColor: Color(0xFF77F7FF),
  ),
  EnvironmentTheme(
    id: 'graveyard',
    name: 'Haunted Graveyard',
    ambience: 'Fog, bats, thunder',
    icon: Icons.dark_mode,
    skyColors: [Color(0xFF05050B), Color(0xFF15162E), Color(0xFF424356)],
    farColor: Color(0xFF1E1D2F),
    midColor: Color(0xFF2F3040),
    foregroundColor: Color(0xFF08070C),
    groundTop: Color(0xFF2A2B2F),
    groundBottom: Color(0xFF111116),
    pipeBase: Color(0xFF34333A),
    pipeRim: Color(0xFF8D7CFF),
    accent: Color(0xFFB9A9FF),
    particleColor: Color(0xFFCFCBFF),
    lightColor: Color(0xFFDED6FF),
  ),
  EnvironmentTheme(
    id: 'candy',
    name: 'Candy Land',
    ambience: 'Sparkles, sugar breeze',
    icon: Icons.cake,
    skyColors: [Color(0xFFFF91C8), Color(0xFFFFD36E), Color(0xFF8DEBFF)],
    farColor: Color(0xFFFFB2DE),
    midColor: Color(0xFFFF7DB6),
    foregroundColor: Color(0xFF7B318D),
    groundTop: Color(0xFFFF8AB8),
    groundBottom: Color(0xFF7A3E8C),
    pipeBase: Color(0xFF8B4A2A),
    pipeRim: Color(0xFFFFF0A0),
    accent: Color(0xFFFF4FB8),
    particleColor: Color(0xFFFFFFFF),
    lightColor: Color(0xFFFFF49C),
  ),
  EnvironmentTheme(
    id: 'jungle',
    name: 'Jungle Adventure',
    ambience: 'Waterfall, rain, insects',
    icon: Icons.park,
    skyColors: [Color(0xFF08311F), Color(0xFF13673F), Color(0xFF93D98B)],
    farColor: Color(0xFF134C34),
    midColor: Color(0xFF1F7B41),
    foregroundColor: Color(0xFF082915),
    groundTop: Color(0xFF347B39),
    groundBottom: Color(0xFF2B1C11),
    pipeBase: Color(0xFFB4A05A),
    pipeRim: Color(0xFF376F2F),
    accent: Color(0xFFFFD45C),
    particleColor: Color(0xFFBFFF75),
    lightColor: Color(0xFFDFFFA5),
  ),
  EnvironmentTheme(
    id: 'space',
    name: 'Space Galaxy',
    ambience: 'Meteors, stars, void hum',
    icon: Icons.public,
    skyColors: [Color(0xFF01020B), Color(0xFF15134F), Color(0xFF5F2D84)],
    farColor: Color(0xFF291A61),
    midColor: Color(0xFF0D1541),
    foregroundColor: Color(0xFF050713),
    groundTop: Color(0xFF22263D),
    groundBottom: Color(0xFF080812),
    pipeBase: Color(0xFF30364F),
    pipeRim: Color(0xFF77A7FF),
    accent: Color(0xFFFF6DF2),
    particleColor: Color(0xFFFFFFFF),
    lightColor: Color(0xFF9CB8FF),
  ),
  EnvironmentTheme(
    id: 'volcano',
    name: 'Volcano Hell',
    ambience: 'Ash, lava, rumble',
    icon: Icons.local_fire_department,
    skyColors: [Color(0xFF160306), Color(0xFF5A0F0B), Color(0xFFFF5A1F)],
    farColor: Color(0xFF341210),
    midColor: Color(0xFF691A12),
    foregroundColor: Color(0xFF130606),
    groundTop: Color(0xFF3C1912),
    groundBottom: Color(0xFF090404),
    pipeBase: Color(0xFF2B1A16),
    pipeRim: Color(0xFFFF4A1C),
    accent: Color(0xFFFFB13B),
    particleColor: Color(0xFFFFB36B),
    lightColor: Color(0xFFFF4A1C),
  ),
  EnvironmentTheme(
    id: 'sakura',
    name: 'Sakura Japan',
    ambience: 'Petals, lanterns, soft wind',
    icon: Icons.local_florist,
    skyColors: [Color(0xFF59325E), Color(0xFFFFA0B7), Color(0xFFFFE5C6)],
    farColor: Color(0xFF7D6A88),
    midColor: Color(0xFFD47E95),
    foregroundColor: Color(0xFF3B2434),
    groundTop: Color(0xFF8D5C5F),
    groundBottom: Color(0xFF3C242C),
    pipeBase: Color(0xFF6D4735),
    pipeRim: Color(0xFFFFA5C1),
    accent: Color(0xFFFFD0DD),
    particleColor: Color(0xFFFFD7E5),
    lightColor: Color(0xFFFFC2A8),
  ),
  EnvironmentTheme(
    id: 'steampunk',
    name: 'Steampunk Factory',
    ambience: 'Steam, gears, brass',
    icon: Icons.precision_manufacturing,
    skyColors: [Color(0xFF25160D), Color(0xFF6B4527), Color(0xFFD49755)],
    farColor: Color(0xFF4D3425),
    midColor: Color(0xFF704827),
    foregroundColor: Color(0xFF1E1510),
    groundTop: Color(0xFF5C4331),
    groundBottom: Color(0xFF1B120C),
    pipeBase: Color(0xFF9B6A35),
    pipeRim: Color(0xFFFFB45C),
    accent: Color(0xFFFFD08A),
    particleColor: Color(0xFFFFE0B2),
    lightColor: Color(0xFFFFB45C),
  ),
  EnvironmentTheme(
    id: 'heaven',
    name: 'Heaven Clouds',
    ambience: 'Feathers, choir glow',
    icon: Icons.cloud,
    skyColors: [Color(0xFF5BA8FF), Color(0xFFE7F4FF), Color(0xFFFFE6A6)],
    farColor: Color(0xFFD8EFFF),
    midColor: Color(0xFFFFFFFF),
    foregroundColor: Color(0xFFFFF7DD),
    groundTop: Color(0xFFFFF7E5),
    groundBottom: Color(0xFFE4C16A),
    pipeBase: Color(0xFFECEAF0),
    pipeRim: Color(0xFFFFC857),
    accent: Color(0xFFFFE189),
    particleColor: Color(0xFFFFFFFF),
    lightColor: Color(0xFFFFE07A),
  ),
  EnvironmentTheme(
    id: 'nightmare',
    name: 'Dark Nightmare',
    ambience: 'Shadows, red lightning',
    icon: Icons.visibility,
    skyColors: [Color(0xFF020103), Color(0xFF240006), Color(0xFF720015)],
    farColor: Color(0xFF140009),
    midColor: Color(0xFF39000B),
    foregroundColor: Color(0xFF050103),
    groundTop: Color(0xFF190509),
    groundBottom: Color(0xFF030101),
    pipeBase: Color(0xFF21070B),
    pipeRim: Color(0xFFFF163D),
    accent: Color(0xFFFF3157),
    particleColor: Color(0xFFFF5A70),
    lightColor: Color(0xFFFF163D),
  ),
];
